- name: Create caddy data directory
  file:
    path: "{{ fz_install_dir }}/caddy"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Copy Caddy certs
  copy:
    src: ../../files/caddy/certs/
    dest: "{{ fz_install_dir }}/caddy/certs/"
    owner: root
    group: root
    mode: '0600'
    remote_src: no

- name: Create Caddyfile
  copy:
    dest: "{{ fz_install_dir }}/caddy/Caddyfile"
    content: |
      {{ external_url }} {
        log
        tls /data/caddy/certs/certificate.crt /data/caddy/certs/private.key
        reverse_proxy * 172.25.0.100:13000
      }
    owner: root
    group: root
    mode: '0600'

- name: Run caddy container
  community.docker.docker_container:
    name: caddy
    image: caddy:2
    restart_policy: unless-stopped
    command: >
      /bin/sh -c "caddy run --config /data/caddy/Caddyfile"
    volumes:
      - "{{ fz_install_dir }}/caddy:/data/caddy"
    network_mode: host
    state: started 