defmodule FzHttp.L7.CoreDnsHosts do
  @moduledoc """
  Generates the hosts file CoreDNS reads to resolve declared L7
  application hostnames to their virtual IPs (ADR-012).

  CoreDNS is configured with the `hosts` plugin and `reload 1s` so
  any rewrite of the file is picked up within a second — no reload
  signal needed. This module writes the file atomically (tmp + rename)
  so CoreDNS never sees a partial state.

  Subscribes to `nexguard:l7:apps`; any `Applications` mutation
  schedules a regenerate on the next message turn. There's no
  debounce — `File.write!` + `File.rename!` of a few-hundred-byte
  hosts file is cheap enough that even a burst from the admin UI
  doesn't matter.

  Singleton-with-name-override per the in-repo GenServer
  convention; tests pass a unique `:path` so the on-disk state of
  one test doesn't leak into another.
  """

  use GenServer
  require Logger

  alias FzHttp.Applications
  alias FzHttp.Applications.Application, as: App
  alias FzHttp.Types
  alias Phoenix.PubSub

  @apps_topic "nexguard:l7:apps"
  @default_path "/etc/nexguard/internal-hosts"
  @header "# generated by FzHttp.L7.CoreDnsHosts — do not edit by hand\n"

  # ── Client API ─────────────────────────────────────────────────

  def start_link(opts \\ []) do
    if opts[:name] do
      GenServer.start_link(__MODULE__, opts, name: opts[:name])
    else
      GenServer.start_link(__MODULE__, opts)
    end
  end

  @doc "Force regenerate NOW. Returns `:ok` after the file is on disk."
  def regenerate, do: regenerate(__MODULE__)
  def regenerate(server), do: GenServer.call(server, :regenerate, 5_000)

  @doc "Current on-disk path the GenServer is rendering to."
  def path(server \\ __MODULE__), do: GenServer.call(server, :path)

  # ── Server callbacks ───────────────────────────────────────────

  @impl GenServer
  def init(opts) do
    path = Keyword.get(opts, :path, @default_path)
    subscribe? = Keyword.get(opts, :subscribe, true)
    write_on_boot? = Keyword.get(opts, :write_on_boot, true)

    if subscribe? do
      PubSub.subscribe(FzHttp.PubSub, @apps_topic)
    end

    state = %{path: path}

    if write_on_boot? do
      send(self(), :regenerate)
    end

    {:ok, state}
  end

  @impl GenServer
  def handle_call(:regenerate, _from, state) do
    {:reply, do_regenerate(state.path), state}
  end

  def handle_call(:path, _from, state), do: {:reply, state.path, state}

  @impl GenServer
  def handle_info(:apps_changed, state) do
    _ = do_regenerate(state.path)
    {:noreply, state}
  end

  def handle_info(:regenerate, state) do
    _ = do_regenerate(state.path)
    {:noreply, state}
  end

  def handle_info(_other, state), do: {:noreply, state}

  # ── Rendering ──────────────────────────────────────────────────

  defp do_regenerate(path) do
    contents =
      [@header | render_lines(Applications.list_enabled_for_bundle())]
      |> IO.iodata_to_binary()

    atomic_write(path, contents)
  end

  defp render_lines(apps) do
    apps
    |> Enum.sort_by(& &1.hostname)
    |> Enum.map(fn %App{hostname: host, virtual_ip: vip} ->
      "#{Types.INET.to_string(vip)} #{host}\n"
    end)
  end

  # Atomic update: write to <path>.tmp, then rename. CoreDNS with
  # `reload 1s` then re-reads the new contents on its next poll.
  defp atomic_write(path, contents) do
    tmp = path <> ".tmp"

    case File.mkdir_p(Path.dirname(path)) do
      :ok ->
        with :ok <- File.write(tmp, contents),
             :ok <- File.rename(tmp, path) do
          :ok
        else
          {:error, reason} = err ->
            Logger.error(
              "[L7] CoreDnsHosts write failed: #{inspect(reason)} (path=#{path})"
            )
            err
        end

      {:error, reason} = err ->
        Logger.error(
          "[L7] CoreDnsHosts mkdir_p failed: #{inspect(reason)} (path=#{path})"
        )
        err
    end
  end
end
