defmodule FzHttp.L7.CoreDnsCorefile do
  @moduledoc """
  Writes `/etc/nexguard/Corefile.generated` from DB-backed org
  settings on every `nexguard:l7:settings` change. CoreDNS is
  bind-mounted at the same path and uses the `reload 1s` plugin
  (see template below) to pick up rewrites without container
  restart.

  Sister to `FzHttp.L7.CoreDnsHosts` which writes the hosts file at
  `/etc/nexguard/internal-hosts` from L7 application VIPs. Both
  share the bind mount `${FZ_INSTALL_DIR}/coredns-hosts:/etc/nexguard`
  declared in `docker-compose.coredns.yml`.

  Tmp-then-rename atomic write so CoreDNS never sees a partial file
  during the rewrite.

  Singleton-with-name-override per the in-repo GenServer convention;
  tests pass a unique `:path` to keep state isolated.
  """

  use GenServer
  require Logger

  alias FzHttp.OrgSettings
  alias Phoenix.PubSub

  @settings_topic "nexguard:l7:settings"
  @default_path "/etc/nexguard/Corefile.generated"
  @header "# generated by FzHttp.L7.CoreDnsCorefile — do not edit by hand\n"

  # ── Client API ─────────────────────────────────────────────────

  def start_link(opts \\ []) do
    if opts[:name] do
      GenServer.start_link(__MODULE__, opts, name: opts[:name])
    else
      GenServer.start_link(__MODULE__, opts)
    end
  end

  @doc "Force regenerate NOW. Returns `:ok` after the file is on disk."
  def regenerate, do: regenerate(__MODULE__)
  def regenerate(server), do: GenServer.call(server, :regenerate, 5_000)

  @doc "Current on-disk path the GenServer is rendering to."
  def path(server \\ __MODULE__), do: GenServer.call(server, :path)

  @doc """
  Pure renderer — pull out of the GenServer so it's testable
  without I/O. Returns the Corefile text.
  """
  @spec render(%{primary: [String.t()], fallback: [String.t()]}) :: String.t()
  def render(%{primary: primary, fallback: fallback}) do
    primary = primary || []
    fallback = fallback || []
    # Safety fallback in case the DB is empty during transient state
    # (e.g. before bootstrap seed runs). 127.0.0.53 is a non-routable
    # placeholder — CoreDNS health check fails immediately, surfacing
    # as :down on the topnav dot rather than silently dropping queries
    # into Cloudflare.
    upstreams =
      case primary ++ fallback do
        []   -> ["127.0.0.53"]
        list -> list
      end
      |> Enum.join(" ")

    @header <>
      """

      . {
        # Explicit bind — don't rely on implicit "all interfaces".
        bind 0.0.0.0

        # EDNS0 UDP buffer size — 1232 bytes is the DNS Flag Day 2020
        # recommended ceiling for VPN-wrapped paths (MTU 1280 minus
        # IPv6/UDP overhead). Larger responses fall back to TCP cleanly
        # instead of fragmenting at the network layer.
        bufsize 1232

        # Drop mDNS-style noise BEFORE upstream — these never resolve
        # publicly and would otherwise spam bind9.
        template ANY ANY local lan home internal corp {
          rcode NXDOMAIN
        }

        # L7 ZTNA VIPs from the hosts file (FzHttp.L7.CoreDnsHosts
        # writes /etc/nexguard/internal-hosts). `fallthrough .` so
        # sister names under declared zones still reach the forward.
        hosts /etc/nexguard/internal-hosts {
          reload 1s
          ttl 30
          fallthrough .
        }

        # Forward — admins edit upstream list via /settings/l7 in the
        # portal. `policy sequential` keeps the cache hot on the first
        # healthy upstream; fail-over is health-check driven, not
        # per-query. `prefer_udp` keeps the fast path on UDP and only
        # escalates to TCP for large responses or when bind9 truncates.
        # `max_concurrent 1000` is the per-CoreDNS-instance ceiling on
        # in-flight upstream queries — bind9 is already exempt from RRL
        # for the gateway IP so we don't need to shape on the CoreDNS
        # side.
        forward . #{upstreams} {
          prefer_udp
          max_concurrent 1000
          health_check 5s
          expire 30s
          policy sequential
        }

        # Cache layer — the main weapon for keeping bind9 traffic
        # low. `success` 16K entries with min TTL 60s clamps records
        # whose origin TTL is set too low (some internal records ship
        # at 5s, which would defeat caching). `denial` keeps NXDOMAIN
        # cached 5min. `serve_stale` makes us survive bind9 outages
        # invisibly. `prefetch` refreshes the hot tail BEFORE expiry
        # so clients never wait on a cache miss.
        cache {
          success 16384 3600 60
          denial 4096 300 30
          serve_stale 1h immediate
          prefetch 10 1m 10%
        }

        # Defensive: catch a misconfigured forward that loops back.
        loop

        # Shuffle multi-IP A/AAAA responses — internal services that
        # return several backend IPs (e.g. systems-internal-ingress
        # returns 4 entries) get client-side load balancing for free.
        loadbalance

        # Logs ONLY errors — full query logging is expensive and we
        # have Prometheus metrics for cache hit rate / forward latency.
        errors

        # Hot-reload THIS Corefile when Phoenix rewrites it. 2s is the
        # CoreDNS minimum (the plugin refuses < 2s with an explicit
        # error).
        reload 2s

        # Prometheus scrape endpoint — cache hit rate, forward latency
        # by upstream, request counts by rcode. Scrape from inside the
        # nexguard network namespace.
        prometheus :9153
      }
      """
  end

  # ── Server ─────────────────────────────────────────────────────

  @impl GenServer
  def init(opts) do
    path = Keyword.get(opts, :path, @default_path)
    subscribe? = Keyword.get(opts, :subscribe, true)
    write_on_boot? = Keyword.get(opts, :write_on_boot, true)

    if subscribe?, do: PubSub.subscribe(FzHttp.PubSub, @settings_topic)

    state = %{path: path}

    if write_on_boot?, do: send(self(), :regenerate)

    {:ok, state}
  end

  @impl GenServer
  def handle_call(:regenerate, _from, state) do
    do_regenerate(state.path)
    {:reply, :ok, state}
  end

  def handle_call(:path, _from, state), do: {:reply, state.path, state}

  @impl GenServer
  def handle_info(:regenerate, state) do
    do_regenerate(state.path)
    {:noreply, state}
  end

  def handle_info({:dns_forward_changed, _payload}, state) do
    do_regenerate(state.path)
    {:noreply, state}
  end

  # L7 enable toggle doesn't change the Corefile but we share the topic.
  def handle_info({:l7_enabled_changed, _}, state), do: {:noreply, state}
  def handle_info(_other, state), do: {:noreply, state}

  # ── Render + write ─────────────────────────────────────────────

  defp do_regenerate(path) do
    settings = OrgSettings.get()
    text = render(%{
      primary:  settings.coredns_forward_to,
      fallback: settings.coredns_forward_to_fallback
    })

    tmp = path <> ".tmp"

    case File.mkdir_p(Path.dirname(path)) do
      :ok ->
        case File.write(tmp, text) do
          :ok ->
            case File.rename(tmp, path) do
              :ok ->
                Logger.info("[CoreDnsCorefile] wrote #{path} (#{byte_size(text)}b)")
                :ok

              {:error, reason} ->
                Logger.error("[CoreDnsCorefile] rename failed: #{inspect(reason)}")
                :error
            end

          {:error, reason} ->
            Logger.error("[CoreDnsCorefile] tmp write failed: #{inspect(reason)}")
            :error
        end

      {:error, reason} ->
        Logger.error("[CoreDnsCorefile] mkdir #{Path.dirname(path)} failed: #{inspect(reason)}")
        :error
    end
  end
end
