defmodule FzHttp.L7.CoreDnsCorefile do
  @moduledoc """
  Writes `/etc/nexguard/Corefile.generated` from DB-backed org
  settings on every `nexguard:l7:settings` change. CoreDNS is
  bind-mounted at the same path and uses the `reload 1s` plugin
  (see template below) to pick up rewrites without container
  restart.

  Sister to `FzHttp.L7.CoreDnsHosts` which writes the hosts file at
  `/etc/nexguard/internal-hosts` from L7 application VIPs. Both
  share the bind mount `${FZ_INSTALL_DIR}/coredns-hosts:/etc/nexguard`
  declared in `docker-compose.coredns.yml`.

  Tmp-then-rename atomic write so CoreDNS never sees a partial file
  during the rewrite.

  Singleton-with-name-override per the in-repo GenServer convention;
  tests pass a unique `:path` to keep state isolated.
  """

  use GenServer
  require Logger

  alias FzHttp.OrgSettings
  alias Phoenix.PubSub

  @settings_topic "nexguard:l7:settings"
  @default_path "/etc/nexguard/Corefile.generated"
  @header "# generated by FzHttp.L7.CoreDnsCorefile — do not edit by hand\n"

  # ── Client API ─────────────────────────────────────────────────

  def start_link(opts \\ []) do
    if opts[:name] do
      GenServer.start_link(__MODULE__, opts, name: opts[:name])
    else
      GenServer.start_link(__MODULE__, opts)
    end
  end

  @doc "Force regenerate NOW. Returns `:ok` after the file is on disk."
  def regenerate, do: regenerate(__MODULE__)
  def regenerate(server), do: GenServer.call(server, :regenerate, 5_000)

  @doc "Current on-disk path the GenServer is rendering to."
  def path(server \\ __MODULE__), do: GenServer.call(server, :path)

  @doc """
  Pure renderer — pull out of the GenServer so it's testable
  without I/O. Returns the Corefile text.
  """
  @spec render(%{primary: [String.t()], fallback: [String.t()]}) :: String.t()
  def render(%{primary: primary, fallback: fallback}) do
    primary = primary || []
    fallback = fallback || []
    # Safety fallback in case the DB is empty during transient state
    # (e.g. before bootstrap seed runs). 127.0.0.53 is a non-routable
    # placeholder — CoreDNS health check fails immediately, surfacing
    # as :down on the topnav dot rather than silently dropping queries
    # into Cloudflare.
    upstreams =
      case primary ++ fallback do
        []   -> ["127.0.0.53"]
        list -> list
      end
      |> Enum.join(" ")

    @header <>
      """

      . {
        # Drop mDNS-style noise BEFORE upstream — these never resolve
        # publicly and would otherwise spam bind9.
        template ANY ANY local lan home internal corp {
          rcode NXDOMAIN
        }

        # L7 ZTNA VIPs from the hosts file (FzHttp.L7.CoreDnsHosts
        # writes /etc/nexguard/internal-hosts). `fallthrough .` so
        # sister names under declared zones still reach the forward.
        hosts /etc/nexguard/internal-hosts {
          reload 1s
          ttl 30
          fallthrough .
        }

        # Forward — admins edit upstream list via /settings/l7 in the
        # portal. `policy sequential` keeps the cache hot on the first
        # healthy upstream; fail-over is health-check driven, not
        # per-query.
        forward . #{upstreams} {
          max_concurrent 100
          health_check 5s
          expire 30s
          policy sequential
        }

        # Cache hardening — see migrations/v3.0.1.md.
        cache {
          success 16384 3600 60
          denial 4096 300 30
          serve_stale 1h immediate
          prefetch 10 1m 10%
        }

        errors
        # `reload 2s` watches THIS Corefile for changes — admins edit
        # upstreams in the portal, Phoenix rewrites this file,
        # CoreDNS picks it up within ~2s. 2s is CoreDNS' minimum;
        # `reload 1s` would refuse to start with
        # `plugin/reload: interval value must be greater or equal to 2s`.
        reload 2s
        log . "{remote}:{port} {>id} {type} {name} -> {rcode} {>rflags} {rsize} {duration}"
      }
      """
  end

  # ── Server ─────────────────────────────────────────────────────

  @impl GenServer
  def init(opts) do
    path = Keyword.get(opts, :path, @default_path)
    subscribe? = Keyword.get(opts, :subscribe, true)
    write_on_boot? = Keyword.get(opts, :write_on_boot, true)

    if subscribe?, do: PubSub.subscribe(FzHttp.PubSub, @settings_topic)

    state = %{path: path}

    if write_on_boot?, do: send(self(), :regenerate)

    {:ok, state}
  end

  @impl GenServer
  def handle_call(:regenerate, _from, state) do
    do_regenerate(state.path)
    {:reply, :ok, state}
  end

  def handle_call(:path, _from, state), do: {:reply, state.path, state}

  @impl GenServer
  def handle_info(:regenerate, state) do
    do_regenerate(state.path)
    {:noreply, state}
  end

  def handle_info({:dns_forward_changed, _payload}, state) do
    do_regenerate(state.path)
    {:noreply, state}
  end

  # L7 enable toggle doesn't change the Corefile but we share the topic.
  def handle_info({:l7_enabled_changed, _}, state), do: {:noreply, state}
  def handle_info(_other, state), do: {:noreply, state}

  # ── Render + write ─────────────────────────────────────────────

  defp do_regenerate(path) do
    settings = OrgSettings.get()
    text = render(%{
      primary:  settings.coredns_forward_to,
      fallback: settings.coredns_forward_to_fallback
    })

    tmp = path <> ".tmp"

    case File.mkdir_p(Path.dirname(path)) do
      :ok ->
        case File.write(tmp, text) do
          :ok ->
            case File.rename(tmp, path) do
              :ok ->
                Logger.info("[CoreDnsCorefile] wrote #{path} (#{byte_size(text)}b)")
                :ok

              {:error, reason} ->
                Logger.error("[CoreDnsCorefile] rename failed: #{inspect(reason)}")
                :error
            end

          {:error, reason} ->
            Logger.error("[CoreDnsCorefile] tmp write failed: #{inspect(reason)}")
            :error
        end

      {:error, reason} ->
        Logger.error("[CoreDnsCorefile] mkdir #{Path.dirname(path)} failed: #{inspect(reason)}")
        :error
    end
  end
end
