defmodule FzHttp.L7.CoreDnsHostsTest do
  # async: false — registered under canonical name in some tests; the
  # GenServer also queries Repo from a spawned process, so shared
  # sandbox mode is needed.
  use FzHttp.DataCase, async: false

  alias FzHttp.ApplicationsFixtures
  alias FzHttp.L7.CoreDnsHosts

  setup do
    tmp_path = Path.join(System.tmp_dir!(), "coredns-hosts-#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm(tmp_path) end)

    start_supervised!(
      {CoreDnsHosts,
       name: CoreDnsHosts, path: tmp_path, subscribe: false, write_on_boot: false}
    )

    {:ok, path: tmp_path}
  end

  describe "regenerate/0" do
    test "writes the header even when no apps are enabled", %{path: path} do
      :ok = CoreDnsHosts.regenerate()

      contents = File.read!(path)
      assert String.starts_with?(contents, "# generated by FzHttp.L7.CoreDnsHosts")
      # No app rows → only the header line.
      assert contents == "# generated by FzHttp.L7.CoreDnsHosts — do not edit by hand\n"
    end

    test "emits `<vip> <hostname>` per enabled app, sorted by hostname", %{path: path} do
      _disabled =
        ApplicationsFixtures.create_application(%{"enabled" => false})

      _enabled_z =
        ApplicationsFixtures.create_application(%{"enabled" => true, "hostname" => "zeta.internal"})

      _enabled_a =
        ApplicationsFixtures.create_application(%{"enabled" => true, "hostname" => "alpha.internal"})

      :ok = CoreDnsHosts.regenerate()

      contents = File.read!(path)
      lines = contents |> String.split("\n", trim: true) |> Enum.drop(1)

      assert length(lines) == 2
      [first, second] = lines

      assert first =~ ~r/^10\.99\.\d+\.\d+ alpha\.internal$/
      assert second =~ ~r/^10\.99\.\d+\.\d+ zeta\.internal$/
    end

    test "atomic write: no leftover .tmp file after success", %{path: path} do
      :ok = CoreDnsHosts.regenerate()
      refute File.exists?(path <> ".tmp")
    end

    test "creates the parent directory if missing", %{} do
      nested =
        Path.join([System.tmp_dir!(), "coredns-nested-#{System.unique_integer([:positive])}", "hosts"])

      on_exit(fn ->
        File.rm(nested)
        File.rmdir(Path.dirname(nested))
      end)

      pid =
        start_supervised!(
          {CoreDnsHosts,
           name: :"hosts_#{System.unique_integer([:positive])}",
           path: nested,
           subscribe: false,
           write_on_boot: false}
        )

      assert :ok = CoreDnsHosts.regenerate(pid)
      assert File.exists?(nested)
    end
  end

  describe "PubSub wiring" do
    test "regenerates on :apps_changed broadcast", %{path: path} do
      # Direct Repo insert (used in other tests above) bypasses the
      # PubSub broadcast — only `Applications.create_application/3`
      # publishes `:apps_changed`. Manually broadcast to mimic the
      # production code path without paying the full context cost.
      pid =
        start_supervised!(
          {CoreDnsHosts,
           name: :"hosts_sub_#{System.unique_integer([:positive])}",
           path: path,
           subscribe: true,
           write_on_boot: false}
        )

      _app =
        ApplicationsFixtures.create_application(%{
          "enabled" => true,
          "hostname" => "watched.internal"
        })

      Phoenix.PubSub.broadcast(FzHttp.PubSub, "nexguard:l7:apps", :apps_changed)

      # :sys.get_state is a synchronous call — by the time it returns,
      # the GenServer has processed all earlier messages in its mailbox
      # including the broadcast.
      _ = :sys.get_state(pid)

      contents = File.read!(path)
      assert contents =~ "watched.internal"
    end
  end
end
