- name: Create postgres data directory
  file:
    path: "{{ fz_install_dir }}/postgres/data"
    state: directory
    owner: 999
    group: 999
    mode: '0700'

- name: Run postgres container
  community.docker.docker_container:
    name: postgres
    image: postgres:15
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: nexguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "{{ database_password }}"
    volumes:
      - "{{ fz_install_dir }}/postgres/data:/var/lib/postgresql/data"
    networks:
      - name: nexguard-network
    purge_networks: yes
    state: started
    user: "999:999"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5 