version: "0.7.36"
external_url: "https://nexguard.local.vn"
default_admin_email: "admin@local.vn"
default_admin_password: "123qwe4566$#!@4"
guardian_secret_key: "qGtwEq9HSpzS0RgTJlByeLyIXnPx1M"
secret_key_base: "1QGVURsQtAZobFliXkv3sxsSQxkeMCag"
live_view_signing_salt: "5v42x8QDBPq2DxFB"
cookie_signing_salt: "stfgdfjQ"
cookie_encryption_salt: "11Ahsve9i"
database_encryption_key: "bwnouk/QBsRs8EQ8/dsfsdf+xBJWpS1Oa8="
database_password: "1sdfgd28csdf86ae17"
wireguard_ipv4_network: "10.0.22.0/24"
wireguard_ipv4_address: "10.0.22.254"
wireguard_ipv6_network: "fd00::/106"
wireguard_ipv6_address: "fd00::1"
telemetry_enabled: "false"
tid: "9e56556fe18c646b"
fz_install_dir: "/opt/nexguard" 